<?php

use Illuminate\Database\Seeder;

class KljucnaRecLinkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $krl=[
            [
                690,
                "https://webdizajn.ict.edu.rs/stranica/pravila-polaganja"
            ],
            [
                693,
                "https://webdizajn.ict.edu.rs/stranica/negativni-bodovi"
            ],
            [
                696,
                "https://webdizajn.ict.edu.rs/stranica/upis-ocena"
            ],
            [
                699,
                "https://webdizajn.ict.edu.rs/stranica/Primeri_zavr%C5%A1nih_i_specijalisti%C4%8Dkih_radova"
            ],
            [
                700,
                "https://webdizajn.ict.edu.rs/informacije-zavrsni-radovi"
            ],
            [
                707,
                "https://webdizajn.ict.edu.rs/materijali/web-dizajn/predavanja"
            ],
            [
                708,
                "https://webdizajn.ict.edu.rs/materijali/web-dizajn/auditorne"
            ],
            [
                709,
                "https://webdizajn.ict.edu.rs/materijali/web-dizajn/lab-vezbe"
            ],
            [
                710,
                "https://webdizajn.ict.edu.rs/materijali/web-dizajn/dopunski-materijali"
            ],
            [
                711,
                "https://webdizajn.ict.edu.rs/stranica/Raspored_kolokvijuma_-_Web_dizajn"
            ],
            [
                712,
                "https://webdizajn.ict.edu.rs/stranica/Ocenjivanje_sajtova_-_Web_dizajn"
            ],
            [
                713,
                "https://webdizajn.ict.edu.rs/materijali/web-dizajn/laboratorijski-kolokvijum"
            ],
            [
                714,
                "https://webdizajn.ict.edu.rs/materijali/web-dizajn/ispiti"
            ],
            [
                715,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Web_dizajn"
            ],
            [
                716,
                "https://webdizajn.ict.edu.rs/materijali/praktikim-iz-web-dizajna/predavanja"
            ],
            [
                717,
                "https://webdizajn.ict.edu.rs/materijali/praktikim-iz-web-dizajna/kodovi-sa-predavanja"
            ],
            [
                718,
                "https://webdizajn.ict.edu.rs/stranica/Ocenjivanje_sajtova_-_Responsive_web_design"
            ],
            [
                719,
                "https://webdizajn.ict.edu.rs/praktikum_wd/ocenjivanje_ispit"
            ],
            [
                720,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Praktikum_iz_Web_dizajna"
            ],
            [
                721,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje1/predavanja"
            ],
            [
                722,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-1/auditorne"
            ],
            [
                723,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-1/dopunski-materijali"
            ],
            [
                724,
                "https://webdizajn.ict.edu.rs/stranica/Raspored_kolokvijuma_-_Web_programiranje"
            ],
            [
                725,
                "https://webdizajn.ict.edu.rs/stranica/Ocenjivanje_sajtova"
            ],
            [
                726,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-1/ispiti"
            ],
            [
                727,
                "https://webdizajn.ict.edu.rs/stranica/Izrada_dokumentacije"
            ],
            [
                728,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Web_programiranje_1"
            ],
            [
                729,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php1/predavanja"
            ],
            [
                730,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php1/auditorne"
            ],
            [
                731,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php1/lab-vezbe"
            ],
            [
                732,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php1/laboratorijski-kolokvijum"
            ],
            [
                733,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php1/ispiti"
            ],
            [
                734,
                "https://webdizajn.ict.edu.rs/stranica/Raspored_kolokvijuma_-_PHP1"
            ],
            [
                735,
                "https://webdizajn.ict.edu.rs/materijali/Web_programiranje_PHP_1_Dopunski_materijali"
            ],
            [
                736,
                "https://webdizajn.ict.edu.rs/stranica/PHP1_Ocenjivanje_Sajtova_1"
            ],
            [
                737,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Web_programiranje_PHP_1"
            ],
            [
                738,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje2/predavanja"
            ],
            [
                739,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje2/auditorne"
            ],
            [
                740,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje2/lab-vezbe"
            ],
            [
                741,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje2/dopunski-materijali"
            ],
            [
                742,
                "https://webdizajn.ict.edu.rs/stranica/Ocenjivanje_sajtova_-_Web_programiranje_2"
            ],
            [
                743,
                "https://webdizajn.ict.edu.rs/stranica/Raspored_kolokvijuma_-_Web_programiranje_2"
            ],
            [
                744,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje2/laboratorijski-kolokvijum"
            ],
            [
                745,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje2/ispiti"
            ],
            [
                746,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Web_programiranje_2"
            ],
            [
                747,
                "https://webdizajn.ict.edu.rs/praktikum_php/predavanja"
            ],
            [
                748,
                "https://webdizajn.ict.edu.rs/praktikum_php/auditorne_vezbe"
            ],
            [
                749,
                "https://webdizajn.ict.edu.rs/praktikum_php/lab_vezbe"
            ],
            [
                750,
                "https://webdizajn.ict.edu.rs/praktikum_php/lab_kolokvijumi"
            ],
            [
                751,
                "https://webdizajn.ict.edu.rs/stranica/Raspored_kolokvijuma_-_Praktikum_iz_Web_programiranja_PHP"
            ],
            [
                752,
                "https://webdizajn.ict.edu.rs/praktikum_php/ocenjivanje_sajtova"
            ],
            [
                753,
                "https://webdizajn.ict.edu.rs/node/468"
            ],
            [
                754,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Praktikum_iz_web_programiranja_PHP"
            ],
            [
                755,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php2/predavanja"
            ],
            [
                756,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php2/auditorne"
            ],
            [
                757,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php2/lab-vezbe"
            ],
            [
                758,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php2/dopunski-materijali"
            ],
            [
                759,
                "https://webdizajn.ict.edu.rs/php2/ocenjivanje-sajtova"
            ],
            [
                760,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php2/laboratorijski-kolokvijum"
            ],
            [
                761,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php2/ispiti"
            ],
            [
                762,
                "https://drive.google.com/drive/folders/1CunTWI2BdxqP6aOqMjwQ5cTmUoInpNN-"
            ],
            [
                763,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Web_programiranje_PHP_2"
            ],
            [
                764,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-asp/predavanja"
            ],
            [
                765,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-asp/auditorne"
            ],
            [
                766,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-asp/ispiti"
            ],
            [
                767,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-asp/laboratorijski-kolokvijum"
            ],
            [
                768,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-asp/dopunski-materijali"
            ],
            [
                769,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-asp/testovi"
            ],
            [
                770,
                "https://drive.google.com/drive/u/0/folders/1Q-rqJTdEbmwtt69sd5zH_iNStes8aS8e"
            ],
            [
                771,
                "https://webdizajn.ict.edu.rs/stranica/ASP_-_kriterijumi_za_projekat"
            ],
            [
                772,
                "https://webdizajn.ict.edu.rs/materijali/praktikum-iz-web-programiranja/predavanja"
            ],
            [
                773,
                "https://webdizajn.ict.edu.rs/materijali/praktikum-iz-web-programiranja/kodovi-sa-predavanja"
            ],
            [
                774,
                "https://webdizajn.ict.edu.rs/stranica/Ocenjivanje_sajtova_0"
            ],
            [
                775,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Praktikum_iz_objektnog_web_programiranja"
            ],
            [
                776,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje/predavanja"
            ],
            [
                777,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje/auditorne"
            ],
            [
                778,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje/lab-vezbe"
            ],
            [
                779,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje/dopunski-materijali"
            ],
            [
                780,
                "https://webdizajn.ict.edu.rs/stranica/Raspored_kolokvijuma_-_Web_programiranje"
            ],
            [
                781,
                "https://webdizajn.ict.edu.rs/stranica/Ocenjivanje_sajtova_-_Web_programiranje"
            ],
            [
                782,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje/laboratorijski-kolokvijum"
            ],
            [
                783,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje/ispiti"
            ],
            [
                784,
                "https://webdizajn.ict.edu.rs/materijali/napredno-web-programiranje/laboratorijske-vezbe"
            ],
            [
                785,
                "https://webdizajn.ict.edu.rs/materijali/napredno-web-programiranje/ispitni-rokovi"
            ],
            [
                786,
                "https://webdizajn.ict.edu.rs/materijali-predavanja"
            ],
            [
                787,
                ""
            ],
            [
                788,
                "https://webdizajn.ict.edu.rs/stranica/Napredno_Web_programiranje_-_Uputstvo_za_izdradu_projekata_0"
            ],
            [
                789,
                "https://webdizajn.ict.edu.rs/materijali/web-tehnologije/predavanja"
            ],
            [
                790,
                "https://webdizajn.ict.edu.rs/materijali/web-tehnologije/predavanja-napredni"
            ],
            [
                791,
                "https://webdizajn.ict.edu.rs/materijali/web-tehnologije/ispiti-napredni"
            ],
            [
                792,
                "https://webdizajn.ict.edu.rs/materijali/web-tehnologije/ispiti"
            ],
            [
                793,
                "https://webdizajn.ict.edu.rs/materijali/web-tehnologije/vezbe"
            ],
            [
                794,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Web_tehnologije"
            ]

        ];
        foreach ($krl as $k) {
            DB::table('kljucna_rec_link')->insert(
                ['kljucnaRecId'=>$k[0],'link'=>$k[1]]
            );
        }
    }
}
