<?php

use Illuminate\Database\Seeder;

class PredmetStavkaPredmetaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $psp=[
            [
                1,
                1,
                "https://webdizajn.ict.edu.rs/materijali/web-dizajn/predavanja"
            ],
            [
                1,
                2,
                "https://webdizajn.ict.edu.rs/materijali/web-dizajn/auditorne"
            ],
            [
                1,
                3,
                "https://webdizajn.ict.edu.rs/materijali/web-dizajn/lab-vezbe"
            ],
            [
                1,
                7,
                "https://webdizajn.ict.edu.rs/materijali/web-dizajn/dopunski-materijali"
            ],
            [
                1,
                6,
                "https://webdizajn.ict.edu.rs/stranica/Raspored_kolokvijuma_-_Web_dizajn"
            ],
            [
                1,
                8,
                "https://webdizajn.ict.edu.rs/stranica/Ocenjivanje_sajtova_-_Web_dizajn"
            ],
            [
                1,
                4,
                "https://webdizajn.ict.edu.rs/materijali/web-dizajn/laboratorijski-kolokvijum"
            ],
            [
                1,
                5,
                "https://webdizajn.ict.edu.rs/materijali/web-dizajn/ispiti"
            ],
            [
                1,
                9,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Web_dizajn"
            ],
            [
                2,
                1,
                "https://webdizajn.ict.edu.rs/materijali/praktikim-iz-web-dizajna/predavanja"
            ],
            [
                2,
                14,
                "https://webdizajn.ict.edu.rs/materijali/praktikim-iz-web-dizajna/kodovi-sa-predavanja"
            ],
            [
                2,
                13,
                "https://webdizajn.ict.edu.rs/stranica/Ocenjivanje_sajtova_-_Responsive_web_design"
            ],
            [
                2,
                12,
                "https://webdizajn.ict.edu.rs/praktikum_wd/ocenjivanje_ispit"
            ],
            [
                2,
                9,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Praktikum_iz_Web_dizajna"
            ],
            [
                3,
                1,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje1/predavanja"
            ],
            [
                3,
                2,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-1/auditorne"
            ],
            [
                3,
                7,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-1/dopunski-materijali"
            ],
            [
                3,
                6,
                "https://webdizajn.ict.edu.rs/stranica/Raspored_kolokvijuma_-_Web_programiranje"
            ],
            [
                3,
                8,
                "https://webdizajn.ict.edu.rs/stranica/Ocenjivanje_sajtova"
            ],
            [
                3,
                5,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-1/ispiti"
            ],
            [
                3,
                15,
                "https://webdizajn.ict.edu.rs/stranica/Izrada_dokumentacije"
            ],
            [
                3,
                9,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Web_programiranje_1"
            ],
            [
                4,
                1,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php1/predavanja"
            ],
            [
                4,
                2,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php1/auditorne"
            ],
            [
                4,
                3,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php1/lab-vezbe"
            ],
            [
                4,
                4,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php1/laboratorijski-kolokvijum"
            ],
            [
                4,
                5,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php1/ispiti"
            ],
            [
                4,
                6,
                "https://webdizajn.ict.edu.rs/stranica/Raspored_kolokvijuma_-_PHP1"
            ],
            [
                4,
                7,
                "https://webdizajn.ict.edu.rs/materijali/Web_programiranje_PHP_1_Dopunski_materijali"
            ],
            [
                4,
                8,
                "https://webdizajn.ict.edu.rs/stranica/PHP1_Ocenjivanje_Sajtova_1"
            ],
            [
                4,
                9,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Web_programiranje_PHP_1"
            ],
            [
                5,
                1,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje2/predavanja"
            ],
            [
                5,
                2,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje2/auditorne"
            ],
            [
                5,
                3,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje2/lab-vezbe"
            ],
            [
                5,
                7,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje2/dopunski-materijali"
            ],
            [
                5,
                8,
                "https://webdizajn.ict.edu.rs/stranica/Ocenjivanje_sajtova_-_Web_programiranje_2"
            ],
            [
                5,
                6,
                "https://webdizajn.ict.edu.rs/stranica/Raspored_kolokvijuma_-_Web_programiranje_2"
            ],
            [
                5,
                4,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje2/laboratorijski-kolokvijum"
            ],
            [
                5,
                5,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje2/ispiti"
            ],
            [
                5,
                9,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Web_programiranje_2"
            ],
            [
                6,
                1,
                "https://webdizajn.ict.edu.rs/praktikum_php/predavanja"
            ],
            [
                6,
                2,
                "https://webdizajn.ict.edu.rs/praktikum_php/auditorne_vezbe"
            ],
            [
                6,
                3,
                "https://webdizajn.ict.edu.rs/praktikum_php/lab_vezbe"
            ],
            [
                6,
                4,
                "https://webdizajn.ict.edu.rs/praktikum_php/lab_kolokvijumi"
            ],
            [
                6,
                6,
                "https://webdizajn.ict.edu.rs/stranica/Raspored_kolokvijuma_-_Praktikum_iz_Web_programiranja_PHP"
            ],
            [
                6,
                8,
                "https://webdizajn.ict.edu.rs/praktikum_php/ocenjivanje_sajtova"
            ],
            [
                6,
                5,
                "https://webdizajn.ict.edu.rs/node/468"
            ],
            [
                6,
                9,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Praktikum_iz_web_programiranja_PHP"
            ],
            [
                7,
                1,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php2/predavanja"
            ],
            [
                7,
                2,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php2/auditorne"
            ],
            [
                7,
                3,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php2/lab-vezbe"
            ],
            [
                7,
                7,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php2/dopunski-materijali"
            ],
            [
                7,
                8,
                "https://webdizajn.ict.edu.rs/php2/ocenjivanje-sajtova"
            ],
            [
                7,
                4,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php2/laboratorijski-kolokvijum"
            ],
            [
                7,
                5,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-php2/ispiti"
            ],
            [
                7,
                11,
                "https://drive.google.com/drive/folders/1CunTWI2BdxqP6aOqMjwQ5cTmUoInpNN-"
            ],
            [
                7,
                9,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Web_programiranje_PHP_2"
            ],
            [
                8,
                1,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-asp/predavanja"
            ],
            [
                8,
                2,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-asp/auditorne"
            ],
            [
                8,
                5,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-asp/ispiti"
            ],
            [
                8,
                4,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-asp/laboratorijski-kolokvijum"
            ],
            [
                8,
                7,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-asp/dopunski-materijali"
            ],
            [
                8,
                18,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje-asp/testovi"
            ],
            [
                8,
                19,
                "https://drive.google.com/drive/u/0/folders/1Q-rqJTdEbmwtt69sd5zH_iNStes8aS8e"
            ],
            [
                8,
                20,
                "https://webdizajn.ict.edu.rs/stranica/ASP_-_kriterijumi_za_projekat"
            ],
            [
                9,
                1,
                "https://webdizajn.ict.edu.rs/materijali/praktikum-iz-web-programiranja/predavanja"
            ],
            [
                9,
                14,
                "https://webdizajn.ict.edu.rs/materijali/praktikum-iz-web-programiranja/kodovi-sa-predavanja"
            ],
            [
                9,
                8,
                "https://webdizajn.ict.edu.rs/stranica/Ocenjivanje_sajtova_0"
            ],
            [
                9,
                9,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Praktikum_iz_objektnog_web_programiranja"
            ],
            [
                10,
                1,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje/predavanja"
            ],
            [
                10,
                2,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje/auditorne"
            ],
            [
                10,
                3,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje/lab-vezbe"
            ],
            [
                10,
                7,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje/dopunski-materijali"
            ],
            [
                10,
                6,
                "https://webdizajn.ict.edu.rs/stranica/Raspored_kolokvijuma_-_Web_programiranje"
            ],
            [
                10,
                8,
                "https://webdizajn.ict.edu.rs/stranica/Ocenjivanje_sajtova_-_Web_programiranje"
            ],
            [
                10,
                4,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje/laboratorijski-kolokvijum"
            ],
            [
                10,
                5,
                "https://webdizajn.ict.edu.rs/materijali/web-programiranje/ispiti"
            ],
            [
                11,
                3,
                "https://webdizajn.ict.edu.rs/materijali/napredno-web-programiranje/laboratorijske-vezbe"
            ],
            [
                11,
                5,
                "https://webdizajn.ict.edu.rs/materijali/napredno-web-programiranje/ispitni-rokovi"
            ],
            [
                11,
                1,
                "https://webdizajn.ict.edu.rs/materijali-predavanja"
            ],
            [
                11,
                22,
                "https://webdizajn.ict.edu.rs/materijali/napredn-web-programiranje/sms-gateway"
            ],
            [
                11,
                21,
                "https://webdizajn.ict.edu.rs/stranica/Napredno_Web_programiranje_-_Uputstvo_za_izdradu_projekata_0"
            ],
            [
                12,
                1,
                "https://webdizajn.ict.edu.rs/materijali/web-tehnologije/predavanja"
            ],
            [
                12,
                16,
                "https://webdizajn.ict.edu.rs/materijali/web-tehnologije/predavanja-napredni"
            ],
            [
                12,
                17,
                "https://webdizajn.ict.edu.rs/materijali/web-tehnologije/ispiti-napredni"
            ],
            [
                12,
                5,
                "https://webdizajn.ict.edu.rs/materijali/web-tehnologije/ispiti"
            ],
            [
                12,
                3,
                "https://webdizajn.ict.edu.rs/materijali/web-tehnologije/vezbe"
            ],
            [
                12,
                9,
                "https://webdizajn.ict.edu.rs/stranica/Online_materijali_-_Web_tehnologije"
            ]
        ];
        foreach ($psp as $p){
            DB::table('predmet_stavka_predmeta')->insert(
                ['predmetID'=>$p[0],"stavka_predmetaID"=>$p[1],"odgovor"=>$p[2]]
            );
        }
    }
}
